name: Generate Datas

on:
 schedule: # execute every 12 hours
  - cron: "* */12 * * *"
 workflow_dispatch:

jobs:
 build:
  name: Jobs to update datas
  runs-on: ubuntu-latest
  steps:
   # Snake Animation
   - uses: Platane/snk@master
    id: snake-gif
    with:
     github_user_name: ${{ github.repository.owner.login }}
     svg_out_path: dist/github-contribution-grid-snake.svg
        # Personalização da animação
        color: ${{ secrets.SNAKE_COLOR }}
        size: ${{ secrets.SNAKE_SIZE }}
        speed: ${{ secrets.SNAKE_SPEED }}
        style: ${{ secrets.SNAKE_STYLE }}

   - uses: crazy-max/ghaction-github-pages@v2.1.3
    with:
     target_branch: output
     build_dir: dist
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
